### ISSUE TITLE
minor: h5 conversion progress bar wrong maximum

### ISSUE THREAD

**Issue by martinschorb** [constantinpape/pybdv#18]
Hi,

the converter does not show the proper maximum shape in the progress bar:

![image](https://user-images.githubusercontent.com/35071867/79836691-cb820500-83b0-11ea-8dfb-c4ed69a1fc50.png)

in this example, it shows 630, while you can see in the line below it is continuing to process further (until 768).

**Comment by martinschorb** [comment]
It does the same with 1920/2058, 120/128, 480/512,30/32 , ...

**Comment by constantinpape** [comment]
Thanks for raising this. I have also noticed this before, there is something not working correctly 
in the way I compute the chunks. I will look into this after implementing the proper 2d support.

**Comment by constantinpape** [comment]
Fixed by #31
