### ISSUE TITLE
anisotropic voxel sizes

### ISSUE THREAD

**Issue by martinschorb** [constantinpape/pybdv#22]
Hi,

a stack with dims XYZ will be mapped into the h5 container with ZXY.

This means that the dimensions for specifying the resolutions should be mapped accordingly.

I think pybdv messes up the X and Y voxel sizes. Not that this really matters a lot, because usually they should be the same, but playing around with these, I noticed some strange behaviour. 
Could you check?

**Comment by constantinpape** [comment]
> I think pybdv messes up the X and Y voxel sizes. Not that this really matters a lot, because usually they should be the same, but playing around with these, I noticed some strange behaviour.
> Could you check?

Good catch, I will try to check it out in the next couple of days.

**Comment by constantinpape** [comment]
I can't reproduce this. When I run the following example code:
```python
x = np.zeros((100, 100, 100))
p = './data.h5'
make_bdv(x, p, resolution=[1., 2., 3.])
```
I get this in the xml:
```
        <voxelSize>
          <unit>pixel</unit>
          <size>3.0 2.0 1.0</size>
        </voxelSize>
```

So input voxel-size (1, 2, 3) (= z,y,x) is mapped to (3, 2, 1) (=x,y,z), as expected.

**Comment by martinschorb** [comment]
Is it really z,y,x ? That would not be a clean permutation. I assumed it was z,x,y. In any case, this order should be clear in the doc.

**Comment by constantinpape** [comment]
> Is it really z,y,x ? That would not be a clean permutation. I assumed it was z,x,y.

Yes, the axes are not permuted, but they are transposed. I.e. ZYX (numpy = C axis order) is mapped to XYZ (java/imglib = F axis order).

> In any case, this order should be clear in the doc.

I agree. The axes orders are always confusing. For starters I will update the doc string of `make_bdv`and `convert_to_bdv`.
