### ISSUE TITLE
attributes no longer supported

### ISSUE THREAD

**Issue by martinschorb** [constantinpape/pybdv#24]
Hi,

I run into 

```

  File "C:\Software\Anaconda3\envs\pyEM\lib\site-packages\pybdv\metadata.py", line 371, in validate_attributes
    xml_ids = [int(child.find('id').text) for child in attribute]

  File "C:\Software\Anaconda3\envs\pyEM\lib\site-packages\pybdv\metadata.py", line 371, in <listcomp>
    xml_ids = [int(child.find('id').text) for child in attribute]

ValueError: invalid literal for int() with base 10: "{'id': 0, 'Projection_Mode': 'Sum', 'isset': 'true', 'min': 0, 'max': 255, 'color': '255 0 0 255'}"

```

And it is filling the xml with the dictionary `{xxx:yyy,zzz:qqq}` instead of proper values.

I am pretty sure this is the newest version (ran `python setup.py install`). How can I make sure it is?

**Comment by martinschorb** [comment]
shit it is some old version...

how can I make sure it is really updated? This is a conda environment that already has pybdv. It seems `python setup.py install` is not doing it.

will try with `pip install -e` and use it directly from the cloned repo.

**Comment by constantinpape** [comment]
> how can I make sure it is really updated? This is a conda environment that already has pybdv. It seems `python setup.py install` is not doing it.

Yes, `python setup.py install` sometimes behaves weird and I also don't quite understand it.

`pip install -e` is the better option.

**Comment by martinschorb** [comment]
Works now.
It is just annoying, because you go and hunt what is wrong until you realize that it came from an old installation.

Is there a quick way in python to determine where a certain function is loaded from? (Similar to `which` in the shell)

**Comment by constantinpape** [comment]
> Is there a quick way in python to determine where a certain function is loaded from? (Similar to `which` in the shell)

I don't know how to do it for a specific function, but it's easy to do it for the package:
```
python -c "print(pybdv.__file__)"
```
And if you want to make sure to get the absolute path:
python -c "import os; print(os.path.abspath(pybdv.__file__))"
