### ISSUE TITLE
Downsampling if already present

### ISSUE THREAD

**Issue by martinschorb** [constantinpape/pybdv#25]
Hi,

I have pyramidal data in the form of individual TIFs.
Is there a way to feed the data directly into the different resolution layers of the container and skip the downsampling?

Or is the downsampling effort negligible compared to the file IO?

**Comment by constantinpape** [comment]
> Is there a way to feed the data directly into the different resolution layers of the container and skip the downsampling?

Currently not possible.

> Or is the downsampling effort negligible compared to the file IO?

I don't think it's completely negligible, but the IO will probably dominate.

**Comment by martinschorb** [comment]
Hi,

agree. With the files I am dealing with it makes no difference.
