### ISSUE TITLE
memmaps while modifying metadata only

### ISSUE THREAD

**Issue by martinschorb** [constantinpape/pybdv#27]
Hi,

I have the feeling that for some reason somewhere in `make_bdv` it reads the memmaps into numpy arrays even when not overwriting the data. I tried to dig inn it but could not spot where exactly it happens. 

I can only clearly see that the h5 files are modified when I run it, even though I only select `metadata` as overwrite parameter.

**Comment by constantinpape** [comment]
It shouldn't touch the data when you set it to `metadata`, but maybe something is going wrong.
Do you have a minimal example to check this?

**Comment by martinschorb** [comment]
blame on me...

I think it happens somewhere before. Still investigating. It is a bit tricky since some `numpy` functionality works on memmaps while others just load the data (without warning obviously).
