### ISSUE TITLE
edit mode and group mode kill each other

### ISSUE THREAD

**Issue by martinschorb** [constantinpape/pybdv#28]
Hi,

when I try to switch from edit mode to group mode (or back) BDV completely locks up.

**Comment by constantinpape** [comment]
I don't understand what you mean by this.
What is edit mode, what is group mode, how is it related to pybdv?

**Comment by martinschorb** [comment]
aaah sorry. It is bdv-playground.

Happens when you constantly convert and discover issues in the viewer at the same time ;-)

**Comment by constantinpape** [comment]
> aaah sorry. It is bdv-playground.
> 
> Happens when you constantly convert and discover issues in the viewer at the same time ;-)

Ok, good :)
