### ISSUE TITLE
Updating version on conda

### ISSUE THREAD

**Issue by K-Meech** [constantinpape/pybdv#41]
@constantinpape Would it be possible to put the latest version of pybdv on conda-forge?
As far as I know, the version with the on the fly processing functions isn't on conda yet. Thanks!

**Comment by constantinpape** [comment]
I just made the release, should be available on conda-forge in a couple of hours, I will ping you then.

**Comment by constantinpape** [comment]
@K-Meech should be available on conda now. (v0.5.2)

**Comment by K-Meech** [comment]
Perfect - thanks @constantinpape!
