### ISSUE TITLE
Feature request: working with dask arrays

### ISSUE THREAD

**Issue by boazmohar** [constantinpape/pybdv#42]
Hi,

Is there any chance to support [dask arrays](www.dask.org), for out of memory datasets this seems like the most popular choice these days.
If you can point me to what needs to change, and you think it is a good addition, I will try to get an initial PR.

Thanks!
Boaz

**Comment by boazmohar** [comment]
@constantinpape zarr just released [2.10.3](https://zarr.readthedocs.io/en/stable/release.html#release-2-10-3), could you make a release for pybdv as well?

Thanks!
Boaz

**Comment by constantinpape** [comment]
Done. Should be on conda-forge soon. I think this is all done now, so I am gonna close this, feel free to reopen this issue or open a new one if something is still missing for full dask support.
