### ISSUE TITLE
data padding

### ISSUE THREAD

**Issue by martinschorb** [constantinpape/pybdv#9]
Hi,

my input data is 2024x2024. Pybvd will generate a 2048x2048 output with padded zeros.
These become obvious in linear interpolation mode as black frames
Can these be something else? NaN 

Or is this a problem of BDV?

Martin

**Comment by constantinpape** [comment]
I am not quite sure, but I don't actively pad the data in pybdv.
The hdf5 dataset is just created with the same shape as the input data, see https://github.com/constantinpape/pybdv/blob/master/pybdv/converter.py#L266.

What you can try is setting the fillvalue to something else in hdf5: http://docs.h5py.org/en/stable/high/dataset.html#Dataset.fillvalue. I am not sure how BDV would interpret this though.

**Comment by constantinpape** [comment]
pybdv does not pad, this is most likely a BDV problem.
